---
- name: learning to template
  gather_facts: yes
  hosts: planet-express

  # vars:
  #        warpmatter: dark matter
  #        spacedollars: 1000000
  #        cargoinv: slurm cola

  tasks:
          - name: fill in ship.cfg.j2 and push to hosts
            template:
                    src: ship.cfg.j2
                    dest: ~/ship.cfg
